// Generated by CoffeeScript 1.3.3
(function() {
  var Logger, LoggerFactory, loggerLevel;

  loggerLevel = {
    NONE: 0,
    INFO: 1
  };

  Logger = (function() {

    function Logger(level) {
      this.level = level;
    }

    Logger.prototype.info = function(message) {
      if (loggerLevel.INFO <= this.level) {
        return console.log('[INFO] - ' + message);
      }
    };

    Logger.prototype.error = function(message) {
      if (loggerLevel.Error <= this.level) {
        return console.log('[ERROR] - ' + message);
      }
    };

    return Logger;

  })();

  LoggerFactory = (function() {

    function LoggerFactory() {}

    LoggerFactory.prototype.buildLogger = function(level) {
      return new Logger(level);
    };

    return LoggerFactory;

  })();

  module.exports.factory = new LoggerFactory;

  module.exports.level = loggerLevel;

}).call(this);
