// Generated by CoffeeScript 1.3.3
(function() {
  var eventSchema, mongoose, sessionSchema;

  mongoose = require('mongoose');

  mongoose.connect('localhost', 'weevent');

  sessionSchema = new mongoose.Schema({
    name: 'String',
    description: 'String',
    date: {
      type: 'Date'
    }
  });

  eventSchema = new mongoose.Schema({
    name: 'String',
    description: 'String',
    startDate: {
      type: 'Date'
    },
    endDate: {
      type: 'Date'
    },
    sessions: [sessionSchema]
  });

  module.exports.Session = mongoose.model('Session', sessionSchema);

  module.exports.Event = mongoose.model('Event', eventSchema);

}).call(this);
